### ISSUE TITLE
Write version to file doesn't work for editable installs 

### ISSUE THREAD

**Issue by henryiii** [pdm-project/pdm-backend#192]
Using the following idiom:

```python
# __init__.py
from ._version import version as __version__
```

And the following config:

```toml
[tool.pdm.version]
source = "scm"
write_to = "cookie_pdm/_version.py"
write_template = "version = '{}'"
```

Editable installs fail:

```bash
pdm install
pdm run pytest
```

```pytb
/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_package.py:5: in <module>
    import cookie_pdm as m
src/cookie_pdm/__init__.py:10: in <module>
    from ._version import version as __version__
ModuleNotFoundError: No module named 'cookie_pdm._version'
```

I'll probably change this to importlib for now in https://github.com/scientific-python/cookie/pull/251.
