### ISSUE TITLE
Can't include data files in built wheel

### ISSUE THREAD

**Issue by ShaiAvr** [pdm-project/pdm-backend#205]
I use pdm to manage my Python library and I need to include some data files that my library will use and the user shouldn't be aware of them. I am using the `src` layout:
```
.
├── pyproject.toml
├── src
│   └── mypackage
│       ├── __init__.py
│       └── lib.py
├── assets
│   └── sample_data
│       └── data.txt

```
I tried to include the `data.txt` file in the wheel according to the instructions of the [docs](https://backend.pdm-project.org/build_config/#wheel-data-files). A simplified version of my `pyproject.toml` is:
```toml
[project]
name = "mypackage"
version = "0.1.0"
requires-python = ">=3.11,<3.13"
readme = "README.rst"
license = { text = "MIT" }

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.build.wheel-data]
data = ["${BUILD_DIR}/assets/**/*"]
```
Running `pdm build` worked, but when I looked at the generated wheel, it only contained the code from `src`. There was nothing from the `assets` folder. Running `pdm build -v` confirms this: it didn't add anything from the `assets` folder. I tried several things like:
```toml
[tool.pdm.build.wheel-data]
data = ["${BUILD_DIR}/assets/*"]
```
```toml
[tool.pdm.build.wheel-data]
data = ["${BUILD_DIR}/assets/**"]
```
My initial attempt was without `${BUILD_DIR}`:
```toml
[tool.pdm.build.wheel-data]
data = ["assets/**/*"]
```
but that gave me `PermissionError`. It said it can't access the `assets` or the `assets/sample_data` folders. I can't understand how this works and how to get my data files in the built wheel. Why using the simple `data = ["assets/**/*"]` causes a `PermissionError`, and using `${BUILD_DIR}` works, but doesn't include the data files?
