### ISSUE TITLE
Support editable install for namespace package

### ISSUE THREAD

**Issue by st1020** [pdm-project/pdm-backend#253]
I have a monorepo project with a base package and multiple namespace packages.

The namespace packages cannot be imported when doing an editable install with pdm-backend. However, it can be imported using setuptools as the build backend.

The project structure is as follows:

```
.
├── packages
│   ├── pkg_a
│   │   ├── pyproject.toml
│   │   └── somepkg
│   │       └── pkg_a
│   │           └── __init__.py
│   └── pkg_b
│       ├── pyproject.toml
│       └── somepkg
│           └── pkg_b
│               └── __init__.py
├── pdm.lock
├── pyproject.toml
└── src
    └── somepkg
        └── __init__.py
```

The `somepkg` is the base package and `pkg_a`, `pkg_b` are two namespace packages.

The `pyproject.toml` of base package is:

```toml
[project]
name = "somepkg"
version = "0.1.0"
dependencies = []
requires-python = ">=3.12"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm.dev-dependencies]
dev = [
    "-e pkg_a @ file:///${PROJECT_ROOT}/packages/pkg_a",
    "-e pkg_b @ file:///${PROJECT_ROOT}/packages/pkg_b",
]

[tool.pdm]
distribution = true
```

The `pyproject.toml` of namespace packages is:

```toml
[project]
name = "pkg_a"
version = "0.0.1"
dependencies = ["somepkg"]

[tool.pdm.build]
includes = ["somepkg/"]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
```

When use setuptools build backend:

```toml
[project]
name = "somepkg"
version = "0.1.0"
dependencies = []
requires-python = ">=3.12"

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pdm.dev-dependencies]
dev = [
    "-e pkg_a @ file:///the_path_of_project/packages/pkg_a",
    "-e pkg_b @ file:///the_path_of_project/packages/pkg_b",
]

[tool.pdm]
distribution = true
```

```toml
[project]
name = "pkg_a"
version = "0.0.1"
dependencies = ["somepkg"]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"
```

I found that this is because the two handle editable installations of namespace packages differently.

The site-packages directory generated by setuptools is as follows:

```
.venv/lib/python3.12/site-packages/
├── __editable__.pkg_a-0.0.1.pth
├── __editable__.pkg_b-0.0.1.pth
├── __editable__.somepkg-0.1.0.pth
├── __editable___pkg_a_0_0_1_finder.py
├── __editable___pkg_b_0_0_1_finder.py
├── _virtualenv.pth
├── _virtualenv.py
├── pkg_a-0.0.1.dist-info
│   └── ...
├── pkg_b-0.0.1.dist-info
│   └── ...
└── somepkg-0.1.0.dist-info
    └── ...
```

And the site-packages directory generated by pdm-backend is as follows: 

```
.venv/lib/python3.12/site-packages/
├── pkg_a.pth
├── pkg_b.pth
├── somepkg.pth
├── _virtualenv.pth
├── _virtualenv.py
├── pkg_a-0.0.1.dist-info
│   └── ...
├── pkg_b-0.0.1.dist-info
│   └── ...
└── somepkg-0.1.0.dist-info
    └── ...
```
